name: mutant

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  mutant:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    - run: bundle exec rake mutant
